# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - adim-gateway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ea4b12cca000401e943c6ebe0b190b76 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_14b70d4341684e93bc7c97242792fd78 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ea4b12cca000401e943c6ebe0b190b76 }}/admin-gateway:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'adim-gateway'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5171e7c5a9bf4b5b82fb7d16b2ce5388 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ea4b12cca000401e943c6ebe0b190b76 }}/admin-gateway:${{ github.sha }}'